### ISSUE TITLE
Symfony 4.x

### ISSUE THREAD

**Issue by nabeelio** [thephpleague/geotools#116]
Hi, it'd be great to be able to get Symfony 4.x support, it's currently locked to 2.x/3.x. It's keeping composer from updating Laravel and other deps to the latest.

**Comment by nabeelio** [comment]
Nevermind, I can use the dev version. Sorry!

**Comment by Nyholm** [comment]
Please try the master out and make a comment on https://github.com/thephpleague/geotools/pull/115

I would like someone else to review that changes except for me.
