### ISSUE TITLE
Invalid URL in repo description?

### ISSUE THREAD

**Issue by rcwsr** [thephpleague/geotools#121]
Is it me or does http://geotools-php.org/ linked in this repo's description redirect to some weird hentai porn and then redirect to google?

**Comment by jeremyvaught** [comment]
lol, it's not just you

**Comment by darrena092** [comment]
Probably a good idea to fix that one pretty soon. A lot of people are going to click (and have clicked) that link in work.

**Comment by frankdejonge** [comment]
I've removed the url from the repo description.
