### ISSUE TITLE
Distance setFrom Error

### ISSUE THREAD

**Issue by blindpenguin** [thephpleague/geotools#122]
Hello there,

i have some trouble calculating the distance between two points. Currently i'm using the latest version of this library in a project for tracking GPS devices. I want to filter out all coordinates, that are roughly in the same space. So i tried to implement the example into my app, only to get an error message. I also tried it in a plain PHP file with the same result.

Error:
`Fatal error: Uncaught TypeError: Argument 1 passed to Geotools\Distance\Distance::setFrom() must implement interface Geotools\Coordinate\CoordinateInterface, null given, called in C:\Users\ferdi\Projekte\php\laravel\topas-tracker\vendor\league\geotools\src\Geotools\Geotools.php on line 66 and defined in C:\Users\ferdi\Projekte\php\laravel\topas-tracker\vendor\league\geotools\src\Geotools\Distance\Distance.php:35 Stack trace: #0 C:\Users\ferdi\Projekte\php\laravel\topas-tracker\vendor\league\geotools\src\Geotools\Geotools.php(66): Geotools\Distance\Distance->setFrom(NULL) #1 C:\Users\ferdi\Projekte\php\laravel\topas-tracker\geotools-test.php(8): Geotools\Geotools->distance(Object(Geotools\Coordinate\Coordinate), Object(Geotools\Coordinate\Coordinate)) #2 {main} thrown in C:\Users\ferdi\Projekte\php\laravel\topas-tracker\vendor\league\geotools\src\Geotools\Distance\Distance.php on line 35`

The plain PHP example looks like this:

`require 'vendor/autoload.php';

$geotools = new \Geotools\Geotools();
$coordA   = new \Geotools\Coordinate\Coordinate([48.8234055, 2.3072664]);
$coordB   = new \Geotools\Coordinate\Coordinate([43.296482, 5.36978]);
$distance = $geotools->distance($coordA, $coordB);

printf("%s\n",$distance->flat()); // 659166.50038742 (meters)
`

Any suggestion?
Thanks.

**Comment by tonicospinelli** [comment]
@blindpenguin use took a look at [Distance topic](https://github.com/thephpleague/geotools#distance) from readme?

your mistake below:
```diff
- $distance = $geotools->distance($coordA, $coordB);
+ $distance = $geotools->distance()->setFrom($coordA)->setTo($coordB);
```

**Comment by blindpenguin** [comment]
Yes, that's what i tried at first. Same error. I'm currently using Xampp with PHP 7.1. Could this be a problem with this lib?

**Comment by tonicospinelli** [comment]
What is version that you installed? I made a test with `0.8.0` version using readme sample and it works for me. PHP 7.2

```shell
php index.php
659166.50038742
659021.90812847
659.02190812846
409.05330679648
2162619.7519272
```

**Comment by blindpenguin** [comment]
Ok, apparently the `@stable` tag installs 0.1.5. I didn't even notice it, because i thought it would install the latest "stable" version. This explains a lot. My bad. Thank you very much, with 0.8.0 it's working just fine.
