### ISSUE TITLE
Domain has expired and was serving explicit content.

### ISSUE THREAD

**Issue by frankdejonge** [thephpleague/geotools#123]
I've removed the url in the description, please remove all other references.

**Comment by philipobenito** [comment]
The only references are in composer.json so I've just removed them.

**Comment by philipobenito** [comment]
https://github.com/thephpleague/geotools/commit/955a6337cc263148300290f059e8af9ee665c9b4

**Comment by Nyholm** [comment]
Im not sure I understand this ticket.

**Comment by frankdejonge** [comment]
@Nyholm the repo pointed to  geotools-php dot org which serves explicit content.

**Comment by Surfoo** [comment]
Fixed in https://github.com/thephpleague/geotools/commit/955a6337cc263148300290f059e8af9ee665c9b4#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34
