### ISSUE TITLE
Call to undefined function League\\Geotools\\BoundingBox\\bccomp()

### ISSUE THREAD

**Issue by ultrasamad** [thephpleague/geotools#126]
I am getting this error on my server. I however don't get it when on local development with xampp.
Do I need to do some additional configuration on my server?

**Comment by Destroy666x** [comment]
http://php.net/manual/en/function.bccomp.php - bcmath is needed

**Comment by ultrasamad** [comment]
@Destroy666x Yh. I solved it by adding that library.
