### ISSUE TITLE
Installation React Loop package version

### ISSUE THREAD

**Issue by ammont** [thephpleague/geotools#130]
Getting the following error when installing geo tools:

` Problem 1
    - Can only install one of: react/event-loop[v1.1.0, 0.4.x-dev].
    - Can only install one of: react/event-loop[0.4.x-dev, v1.1.0].
    - Can only install one of: react/event-loop[0.4.x-dev, v1.1.0].
    - league/geotools 0.8.0 requires react/event-loop 0.4.* -> satisfiable by react/event-loop[0.4.x-dev].
    - Installation request for league/geotools ^0.8 -> satisfiable by league/geotools[0.8.0].
    - Installation request for react/event-loop 1.1.0 -> satisfiable by react/event-loop[v1.1.0].
`

Seems geotools is using a very old version of the react-loop which makes it impossible to be used by latest API Platform.

**Comment by stephanvierkant** [comment]
Feel free to open a pull request.
