### ISSUE TITLE
Warning thrown in PHP 7.4 when using small coordinates

### ISSUE THREAD

**Issue by darrylkuhn** [thephpleague/geotools#144]
PHP 7.4 no longer suppresses malformed input for bcmath functions. See https://www.php.net/manual/en/migration74.incompatible.php. This results in a warning when creating a Polygon which contains a small non-zero coordinate. For example:
```php
new Polygon( [[0,0],[1,0],[1,1],[0,-.000001]] );
```
results in the following warning: `PHP Warning:  bccomp(): bcmath function argument is not well-formed in /srv/vendor/league/geotools/src/BoundingBox/BoundingBox.php on line 119`. 

This is because `League\Geotools\Coordinate\Coordinate::normalizeLatitude()` and `League\Geotools\Coordinate\Coordinate::normalizeLontigude()` cast the value to a double which (depending on the size of the number) is represented using scientific notation (e.g. `-.000001` is represented as `-1.0E-6`). It is well documented that bcmath is not able to parse numbers in scientific notation hence the warning. 

I believe the correct fix would be to use `sprintf` to cast the values to strings so they can be used by bcmath though I am open to other suggestions. Would a PR addressing this be welcome?

**Comment by Surfoo** [comment]
Hello @darrylkuhn,

Yes, you can submit a pull request, thank you :)

**Comment by martynaszaliaduonis** [comment]
@Surfoo @Nyholm Are you already planned to release a new version with the fix?

**Comment by Nyholm** [comment]
This issue was fixed in #149. 

Sure, lets prepare a release.
