### ISSUE TITLE
dependence react/event-loop 0.4.* version update ?

### ISSUE THREAD

**Issue by BUGOVER** [thephpleague/geotools#148]
do you plan to update the version in the near futureDo you plan to update the version of react / event-loop: 0.4. * to 1.0.0 in the near future, otherwise ue conflicts with the rest of the packages, the first version of react / event-loop has been out for a long time.

**Comment by coreation** [comment]
+1 for this, a lot of packages have been upgrading to v1 of react / event-loop.
