### ISSUE TITLE
point destination example doesn't work

### ISSUE THREAD

**Issue by CeeJayMI** [thephpleague/geotools#161]
thanks for this library, it's a lifesaver!

example is:
$geotools = new \Geotools\Geotools();
$destinationPoint = $geotools->from($coordA)->point()->destination(180, 200000); // \Geotools\Coordinate\Coordinate

throws:
Geotools\Point\Point::setTo(): Argument #1 ($to) must be of type Geotools\Coordinate\CoordinateInterface, null given

working example:
$geotools = new \Geotools\Point\Point();
$destinationPoint = $geotools->setFrom($coordA)->destination(180, 200000); // \Geotools\Coordinate\Coordinate

**Comment by Surfoo** [comment]
Hello,

Since the 0.7.0, `Point` class was replaced by `Vertex` class, here a working example : 

    $geotools = new \League\Geotools\Geotools();
    $coordA   = new \League\Geotools\Coordinate\Coordinate([48.8234055, 2.3072664]);

    $destinationPoint = $geotools->vertex()->setFrom($coordA)->destination(180, 200000); // \League\Geotools\Coordinate\Coordinate
    printf("%s\n", $destinationPoint->getLatitude()); // 47.026774931761
    printf("%s\n", $destinationPoint->getLongitude()); // 2.3072664
