### ISSUE TITLE
Add Geometry class

### ISSUE THREAD

**Issue by toin0u** [thephpleague/geotools#17]
* polygon's centroïd
* bounding box of a polygon
* create a polygon from an array for coordinates
* are 2 lines crossing each other ?
* ...

**Comment by remdan** [comment]
+1
I looking for polygon centroid...

**Comment by toin0u** [comment]
I close this as it's partially done..
@remdan Feel free to create an other issue on centroid if it's still relevant.

**Comment by acidjazz** [comment]
@toin0u any update on getting a centroid?
