### ISSUE TITLE
php composer require league/geotools=@stable?

### ISSUE THREAD

**Issue by tacman** [thephpleague/geotools#178]
Is that really the recommended way to install?  Shouldn't the user simply set minimum-stability and prefer-stable in composer.json?

In the github workflow tools, I'm getting this warning:
```
Run composer validate
./composer.json is valid for simple usage with Composer but has
strict errors that make it unable to be published as a package
See https://getcomposer.org/doc/04-schema.md for details on the schema
# Publish errors
# General warnings
- require.league/geotools : unbound version constraints (@stable) should be avoided
```

Great tools, thanks for publishing them.  I'm just wondering why the non-standard installation instructions, works fine without the stable reference.

**Comment by Un1matr1x** [comment]
I guess it's made so, that the instructions doesn't need constant updates with version chances.

You might also noticed the "PRO-TIP" from added via 5701100 , which tells you about the valid alternativ

**Comment by Surfoo** [comment]
README.md ha been fixed, thanks!
