### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by maxyc-webber** [thephpleague/geotools#186]
php -v
PHP 8.2.0 (cli) (built: Dec 21 2022 05:43:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

-------------------

/var/www/symfony$ composer require league/geotools=@stable -W
./composer.json has been updated
Running composer update league/geotools --with-all-dependencies
Loading composer repositories with package information                                                                                                                                                             Restricting packages listed in "symfony/symfony" to "6.2.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/geotools[1.0.0, ..., 1.1.0] require cache/array-adapter ^1.0 -> satisfiable by cache/array-adapter[1.0.0, ..., 1.2.0].
    - league/geotools[0.1.0, ..., 0.1.7] require willdurand/geocoder 1.2.* -> found willdurand/geocoder[1.2.0, 1.2.1] but these were not loaded, likely because it conflicts with another require.
    - league/geotools[0.1.8, ..., 0.2.4] require willdurand/geocoder ~1.0 -> found willdurand/geocoder[1.0.0, ..., 1.7.1] but these were not loaded, likely because it conflicts with another require.
    - league/geotools 0.3.0 requires willdurand/geocoder ~2.0 -> found willdurand/geocoder[2.0.0, ..., 2.8.2] but these were not loaded, likely because it conflicts with another require.
    - league/geotools 0.3.1 requires willdurand/geocoder ~2.3 -> found willdurand/geocoder[2.3.0, ..., 2.8.2] but these were not loaded, likely because it conflicts with another require.
    - league/geotools[0.3.2, ..., 0.4.0] require willdurand/geocoder ~2.4 -> found willdurand/geocoder[2.4.0, ..., 2.8.2] but these were not loaded, likely because it conflicts with another require.
    - league/geotools[0.5.0, ..., 0.7.0] require willdurand/geocoder ~3.2 -> found willdurand/geocoder[v3.2.0, v3.3.0, v3.3.1, v3.3.2] but these were not loaded, likely because it conflicts with another require.
    **- league/geotools[0.8.0, ..., 0.8.1] require php ^7.0 -> your php version (8.2.0) does not satisfy that requirement.**
    - league/geotools[0.8.2, ..., 0.8.3] require psr/cache ^1.0 -> found psr/cache[1.0.0, 1.0.1] but these were not loaded, likely because it conflicts with another require.
    - cache/array-adapter 1.1.0 require psr/cache ^1.0 -> found psr/cache[1.0.0, 1.0.1] but these were not loaded, likely because it conflicts with another require.
    - cache/array-adapter[1.0.0, ..., 1.0.1] require php ^5.6 || ^7.0 -> your php version (8.2.0) does not satisfy that requirement.
    - cache/array-adapter[1.1.x-dev, ..., 1.2.0] require psr/cache ^1.0 || ^2.0 -> found psr/cache[1.0.0, 1.0.1, 2.0.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires league/geotools @stable -> satisfiable by league/geotools[0.1.0, ..., 0.8.3, 1.0.0, 1.1.0].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Surfoo** [comment]
README.md ha been fixed, thanks!
