### ISSUE TITLE
"Point" terminology

### ISSUE THREAD

**Issue by dave1010** [thephpleague/geotools#39]
An instance of the `Point` class has an origin and a destination coordinate. This seems like poor naming, as in most GIS implementations (and semantically) a point has exactly 1 coordinate.

Having a quick Google around, either MultiPoint or Line would make more sense, although these are generally not limited to 2 coordinates.

Maybe I'm viewing the class wrongly and it shouldn't be thought of a value object at all but a coordinate service / calculator. In that case perhaps `Point` should be in a different namespace that implies it's a tool rather than a value object, which is what `Convert` does.

Feel free to close as wontfix, as I guess "geotools" implies that this is a collection of tools, as opposed to a component to drop into the business domain.

**Comment by codisart** [comment]
Hi sorry to intrude into the conversation but shouldn't the name of this class be `Vertex` ?

**Comment by toin0u** [comment]
@codisart I think your proposition sounds legit - it might be the best actually :)

**Comment by toin0u** [comment]
Fixed by https://github.com/thephpleague/geotools/pull/68 - Thanks @codisart !

**Comment by remi-san** [comment]
Hey,

I think there's been a misunderstanding there. What you described is an Edge, not a Vertex.

An edge is the line segment joining 2 vertices. Vertices are just a point, not a line.

So, it's going to be a new BC break, but I think that we should rename it once more.

**Comment by codisart** [comment]
Fudge, I think you right.

I thought vertex was the translation needed.
But, I just checked and in fact it is vector which is used to describe a segment with a direction.

(I'm french and vertex is so near the french word "vecteur" that I did check the right meaning of the word, I am so sorry.)

**Comment by remi-san** [comment]
Here's my proposition to fix it: [PR #87](https://github.com/thephpleague/geotools/pull/87)
