### ISSUE TITLE
Possibly use a cache in the CLI for geocoder

### ISSUE THREAD

**Issue by Fil** [thephpleague/geotools#41]
I would love to see an option (on by default?) to use a cache in the CLI for geocoder.

`geotools --cache=yes geocoder:geocode "My Favorite Hiding Place"`

**Comment by toin0u** [comment]
@Fil A very simple version is added now as you can see here: https://github.com/thephpleague/geotools/commit/8bad3f4ef6d3279e235a2ce315e43c610530d2be :)

**Comment by Fil** [comment]
:+1:
