### ISSUE TITLE
Boost symfony/console version to ~3.*

### ISSUE THREAD

**Issue by sergey-nagaytsev** [thephpleague/geotools#55]
Had to downgrade it in my project to use this package.

What if someone uses 3.* features and can't drop them ?

**Comment by toin0u** [comment]
@sergey-nagaytsev thanks for your comment but `geotools` uses `~2.0` atm and the version `3.0` is not released yet. Let's see what we can do efter its release. Maybe you can provide a PR or something like that?

**Comment by sergey-nagaytsev** [comment]
I think the original authors are more eligible than me for precise version choice, since you better know what features you use from it. So I did issue, not PR.

However, 'unreleased' is good argument to hold back. Sorry for overlooking this. Maybe, maximum stable in 2.* ? I just tried "~2@stable" and it installed "2.6.4". Should I PR this ?

P.S. Is there any any feature in GitHub to provide patches, or cloning for few-letters changes is the only option ?

P.S.2 Is there any feature in any collaborative website to notify about version shift in packages, or to check if certain package or package set meets some criteria about versions, like "max stable" ?

**Comment by toin0u** [comment]
Actually `~2.4` means `>=2.4 <3.0`. So it's normal that you installed the last stable version `2.6.4`.

There is a edit button in the file you want to change.

I think you're looking for this: https://www.versioneye.com/php/league:geotools/0.4.0 :)
