### ISSUE TITLE
normalizeLatitude and normalizeLongitude examples in docs don't work as-is

### ISSUE THREAD

**Issue by hguiney** [thephpleague/geotools#59]
From the README:

> Latitudes below -90.0 or above 90.0 degrees are capped through
> `\League\Geotools\Coordinate\Coordinate::normalizeLatitude()`.
> Longitudes below -180.0 or abode 180.0 degrees are wrapped through
> `\League\Geotools\Coordinate\Coordinate::normalizeLongitude()`.

However, when called this way:

> Non-static method League\Geotools\Coordinate\Coordinate::normalizeLatitude() should not be called statically

Source has them as plain public methods. So either the source should change (PR submitted) or the docs should.

**Comment by toin0u** [comment]
Hi @hguiney, I understand why you mean. The `::` is misleading because you're right it could be `static` but it's not what it means. It only a full qualified method name. If the method was static then we should precise it.
Thanks for the PR - I would prefer a PR for the doc :)
