### ISSUE TITLE
Clear exception if provider limit occurs

### ISSUE THREAD

**Issue by JHGitty** [thephpleague/geotools#63]
Is there any clear exception which will be thrown if the provider limits has been reached?

For example Google Maps Geocoding API limits:
https://developers.google.com/maps/documentation/geocoding/intro#Limits

I want to stop my script in a nice way if this limit occurs so I need a clear way to know if this limit is reached. How to handle it the right way?

**Comment by amenadiel** [comment]
I just came upon geotools today. I had been using php geocoder up to now.

However, in PHP geocoder there's a pretty clear [QuotaExceeded](https://github.com/geocoder-php/Geocoder/blob/master/src/Geocoder/Exception/QuotaExceeded.php) exception and if you specifically catch one of those you could discard any further error

**Comment by toin0u** [comment]
@JHGitty as @amenadiel said, you need to catch the exception thrown by the `GoogleMapsProvider` see: https://github.com/geocoder-php/Geocoder/blob/master/src%2FGeocoder%2FProvider%2FGoogleMaps.php#L168
