### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by dpmancus** [thephpleague/geotools#65]
Hello,

using this library ("version": "0.4.0") i found a division by zero when calculating distance with vincenty algorithm, when both points have latitude 0 (stand on equator)

here the code:

```php
$geotools = new \League\Geotools\Geotools();
$coordA   = new \League\Geotools\Coordinate\Coordinate(array(0, 30));
$coordB   = new \League\Geotools\Coordinate\Coordinate(array(0, 20));

$distance = $geotools->distance()->setFrom($coordA)->setTo($coordB)->in('km')->vincenty();
//Division by zero in vendor/league/geotools/src/Distance/Distance.php:194 {$cos2SigmaM = $cosSigma - 2 * $sinU1 * $sinU2 / $cosSqAlpha;}
```

Please let me know if you need additional info.

**Comment by toin0u** [comment]
@dpmancus Thanks reporting it - this PR https://github.com/thephpleague/geotools/pull/66 fixes the issue :)
