### ISSUE TITLE
Cache adapter for Credis library

### ISSUE THREAD

**Issue by djmattyg007** [thephpleague/geotools#74]
A lot of Magento 1 projects use the Credis library, due its use as a cache and sessions backend in popular extensions that are now included in its core. It would be nice if there was an adapter for Credis to sit alongside the Predis adapter, so that an existing Credis_Client object could be passed in and used as a cache.

See https://github.com/colinmollenhour/credis

I am happy to develop this adapter, and am mostly putting this forward to discuss what the name of the class for this adapter should be so as to avoid naming conflicts with the existing Predis adapter.

**Comment by toin0u** [comment]
Hi @djmattyg007 - sorry for my late response.
I'm note sure as it's easy to add its own cache adapter. I think it's also because I don't know the Magento world that much. If we get some "vote" for this adapter - we could integrate it into the lib. Is that ok for you?

**Comment by djmattyg007** [comment]
Sorry if it wasn't clear - this isn't specific to Magento. The Credis library is an alternative to Predis. There is nothing specific to Magento within the library. I only mentioned Magento because it's one place where I know it has become quite popular.

I'm not quite sure what you mean by a vote for an adapter? Who would vote and why?

**Comment by toin0u** [comment]
I misunderstood :) If it's an alternative to Predis - I'm fine with that!

By "vote" I meant - if some other people needs that feature - they can "vote" to add it :)

**Comment by Nyholm** [comment]
Im closing this since we use PSR6 now.
