### ISSUE TITLE
Compatibility with Symfony 3.0

### ISSUE THREAD

**Issue by guilro** [thephpleague/geotools#78]
Geotools depends on symfony/serializer ~2.7, which means symfony/serializer >=2,7, <3.0.

This makes impossible to use Geotools in a Symfony 3.0 project.

**Comment by XavRsl** [comment]
+1

**Comment by toin0u** [comment]
@guilro & @XavRsl Thanks to @GrahamCampbell he made the patch for that https://github.com/thephpleague/geotools/pull/76 :)

**Comment by toin0u** [comment]
@guilro @XavRsl If you used the `Vertex` class instead of the `Point` one. It's safe to bump to `0.7.0` here https://github.com/thephpleague/geotools/releases/tag/0.7.0 :)
