### ISSUE TITLE
composer error for symfony serializer (sf 3.0.1)

### ISSUE THREAD

**Issue by Venzon** [thephpleague/geotools#80]
composer update gives mu such error while updating to sf 3.0.1

```
league/geotools 0.6.0 requires symfony/serializer ~2.7 -> satisfiable by symfony/symfony[v2.7.9], symfony/serializer[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - Can only install one of: symfony/symfony[v3.0.0, v2.7.9].
```

**Comment by toin0u** [comment]
@Venzon Which version are you using? Have you tried `dev-master`? https://asciinema.org/a/bvotdyne78xluhv0gd6jsco5f here is the commit https://github.com/thephpleague/geotools/pull/76/files

**Comment by Venzon** [comment]
@toin0u I try to install sf 3.0.1 and symfony/serializer is also 3.0.1

are you sure that "symfony/serializer" : "~2.7|~3.0" allows install 3.0.1 ?

**Comment by Venzon** [comment]
@toin0u 
all works fine for dev-master but not for 0.6.0
we prolly need release bump
closing issue then

**Comment by toin0u** [comment]
@Venzon Thanks! I'll bump it asap

**Comment by toin0u** [comment]
@Venzon here you go https://github.com/thephpleague/geotools/releases/tag/0.7.0 :)

**Comment by Venzon** [comment]
@toin0u thank you

**Comment by andreichirkunovgoon** [comment]
How do you use it? Without declaring it inside of AppKernel.php I get following error message:
Attempted to load class "Polygon" from namespace "League\Geotools".
Did you forget a "use" statement for "League\Geotools\Polygon\Polygon"

 {
        require_once  '/var/www/symfony/vendor/autoload.php';


        $polygon = new \League\Geotools\Polygon([
            [48.9675969, 1.7440796],
            [48.4711003, 2.5268555],
            [48.9279131, 3.1448364],
            [49.3895245, 2.6119995],
        ]);....
