### ISSUE TITLE
Missing geometries

### ISSUE THREAD

**Issue by remievaneos** [thephpleague/geotools#81]
Could we imagine adding such geometries as MultiPolygon, Point (the real one this time), MultiPoint, Line, MultiLine, Curve, etc.?

And shouldn't we bind all the types of Geometry under a same interface? (a bit like what's done in the geotools lib in java: http://docs.geotools.org/stable/userguide/library/jts/geometry.html)

If that's something you'd want, I'd be happy to submit a PR afterwards.

**Comment by toin0u** [comment]
@remievaneos Thank you for proposition! I think it could be a great addition :+1:
